### ISSUE TITLE
Windows Wallet

### ISSUE THREAD

**Issue by Hubbedbub** [dogethdev/dogethereum#1]
A simple Wallet so people can get a receive to wallet address to use for mining.

Not all of us are programmers, we do know a little coding. But come folks, just slapping out a "do this make that use Linux only get this if you know what you are doing or were birthed from a silicone chip factory" doesn't make anyone want to further advance any crypto.

A simple click to download, click to install, ask for install location and default to normal locations. 

_Remember most users don't code, they barely know how to use Windows, and the think Linux is Charley Brown's friend._

**Comment by dogethdev** [comment]
you will see how to add dogether to your wallet on our website
https://dogether.dog/
